### ISSUE TITLE
Improve git submodule

### ISSUE THREAD

**Issue by piperoc** [PikachuHyA/yalantinglibs_as_submodule_demo#1]
@PikachuHyA  
first of all, thank you so much for the effort. It's really great that you take the time to test this.

I would like to offer some suggestions for improvement (I can send my files if needed).

In most cases, the project would be organized a little more.

For example:

**Step 1**: create my project directory `mkdir ~/code/awesome-solution` and `cd ~/code/awesome-solution`.

**Step 2**: make it a git repo by calling `git init` (this will initilize and empty git repo)

**Step 3**: add the library as a **_true submodule_** with ` git submodule add https://github.com/alibaba/yalantinglibs.git` .
At this point you should have a file system structure like: 
```
awesome-solution
├── .git
├── .gitmodules
└── yalantinglibs
```
This is important, because this way you can keep the submodule synced better and you don't have to actually keep the submodule files in your project origin.

**Step 4**: there are often more than one project using the library in the solution. In my case (like in your demo), there would be a client app and a server app that both use the library. Those apps would be separate projects, so my file system will start looking like:

```
awesome-solution
├── CMakeLists.txt
├── client
│   ├── CMakeLists.txt
│   ├── client.cpp
│   ├── service.h
├─── server
│    ├── CMakeLists.txt
│    ├── server.cpp
│    ├── service.h
└─── yalantinglibs
```

**Setp 5**: here's my root `CMakeLists.txt` (in my case it's very important to set the compiler flags as I'm running g++ 10.3.0)

```cmake
cmake_minimum_required(VERSION 3.15)

project(awesome-solution)


set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcoroutines")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_subdirectory(client)
add_subdirectory(server)
add_subdirectory(yalantinglibs)
```

Everything builds and run correctly on my Ubuntu 20.04 with GCC 10.3.0.

Great work! 👍

**Comment by PikachuHyA** [comment]
@piperoc 

Awesome, you are definitely a genius!

I will add your tutorial to the official  yalantinglibs website.

Thank you very much.

**Comment by PikachuHyA** [comment]
hi, I have updated the demo code.
